In [9]:
import pandas as pd
dat_csv = pd.read_csv(r'C:\Users\usuario\OneDrive\Desktop\3! Cuatrimestre\03 - Aprendizaje Automático\01 - Ejercicios\empleados.csv', encoding="ISO-8859-1")
dat_csv

   id   Nombre Genero  Sueldo
0   1     Juan      m   10000
1   2    Ramon      m   20000
2   3     Anna      f   10500
3   4  Julieta      f   13000
4   5    Pablo      m   30000
5   6    Pedro      m   10500
6   7     Gaby      f   11000
7   8  Cecilia      f   27000

In [6]:
dat_csv.head()

   id   Nombre Genero  Sueldo
0   1     Juan      m   10000
1   2    Ramon      m   20000
2   3     Anna      f   10500
3   4  Julieta      f   13000
4   5    Pablo      m   30000

In [12]:
dat_csv = pd.read_csv(
    r'C:\Users\usuario\OneDrive\Desktop\3! Cuatrimestre\03 - Aprendizaje Automático\01 - Ejercicios\empleados.csv',
    encoding="ISO-8859-1",
    header=None
)

dat_csv

    0        1       2       3
0  id   Nombre  Genero  Sueldo
1   1     Juan       m   10000
2   2    Ramon       m   20000
3   3     Anna       f   10500
4   4  Julieta       f   13000
5   5    Pablo       m   30000
6   6    Pedro       m   10500
7   7     Gaby       f   11000
8   8  Cecilia       f   27000

In [13]:
dat_csv = pd.read_csv(
    r'C:\Users\usuario\OneDrive\Desktop\3! Cuatrimestre\03 - Aprendizaje Automático\01 - Ejercicios\empleados.csv',
    encoding="ISO-8859-1",
    header=3
)

dat_csv

   3     Anna  f  10500
0  4  Julieta  f  13000
1  5    Pablo  m  30000
2  6    Pedro  m  10500
3  7     Gaby  f  11000
4  8  Cecilia  f  27000

In [14]:
dat_csv = pd.read_csv(
    r'C:\Users\usuario\OneDrive\Desktop\3! Cuatrimestre\03 - Aprendizaje Automático\01 - Ejercicios\empleados.csv',
    encoding="ISO-8859-1",
    index_col='id'
)

dat_csv

     Nombre Genero  Sueldo
id
1      Juan      m   10000
2     Ramon      m   20000
3      Anna      f   10500
4   Julieta      f   13000
5     Pablo      m   30000
6     Pedro      m   10500
7      Gaby      f   11000
8   Cecilia      f   27000

In [15]:
dat_csv = pd.read_csv(
    r'C:\Users\usuario\OneDrive\Desktop\3! Cuatrimestre\03 - Aprendizaje Automático\01 - Ejercicios\empleados.csv',
    encoding="ISO-8859-1",
    usecols=['Nombre', 'Sueldo']
)

dat_csv.head()

    Nombre  Sueldo
0     Juan   10000
1    Ramon   20000
2     Anna   10500
3  Julieta   13000
4    Pablo   30000

In [16]:
dat_csv = pd.read_csv(
    r'C:\Users\usuario\OneDrive\Desktop\3! Cuatrimestre\03 - Aprendizaje Automático\01 - Ejercicios\empleados.csv',
    encoding="ISO-8859-1",
    skiprows=[1,4]
)

dat_csv

   id   Nombre Genero  Sueldo
0   2    Ramon      m   20000
1   3     Anna      f   10500
2   5    Pablo      m   30000
3   6    Pedro      m   10500
4   7     Gaby      f   11000
5   8  Cecilia      f   27000

In [17]:
dat_csv = pd.read_csv(
    r'C:\Users\usuario\OneDrive\Desktop\3! Cuatrimestre\03 - Aprendizaje Automático\01 - Ejercicios\empleados.csv',
    encoding="ISO-8859-1",
    nrows=3
)

dat_csv

   id Nombre Genero  Sueldo
0   1   Juan      m   10000
1   2  Ramon      m   20000
2   3   Anna      f   10500

In [18]:
dat_csv = pd.read_csv(
    r'C:\Users\usuario\OneDrive\Desktop\3! Cuatrimestre\03 - Aprendizaje Automático\01 - Ejercicios\empleados.csv',
    encoding="ISO-8859-1"
)

dat_csv.query('2 < id < 6')

   id   Nombre Genero  Sueldo
2   3     Anna      f   10500
3   4  Julieta      f   13000
4   5    Pablo      m   30000

In [19]:
# Importamos las librerías necesarias
import pandas as pd
import numpy as np

# Cargamos el archivo CSV desde la ruta correcta
dat_csv = pd.read_csv(
    r'C:\Users\usuario\OneDrive\Desktop\3! Cuatrimestre\03 - Aprendizaje Automático\01 - Ejercicios\empleados.csv',
    encoding="ISO-8859-1"
)

# Seleccionamos las columnas de interés
datos_x = dat_csv['Nombre']
datos_y = dat_csv['Genero']

# Creamos listas vacías
x = []
y = []

# Recorremos la columna "Nombre" y guardamos los valores en la lista x
for i in datos_x:
    x.append(i)

# Recorremos la columna "Genero" y guardamos los valores en la lista y
for j in datos_y:
    y.append(j)

# Mostramos las listas generadas
print(x)
print(y)

# Convertimos la lista x en un array de NumPy
x_array = np.array(x)

# Mostramos el tipo de dato del array
print(type(x_array))

# Mostramos el contenido del array
print(x_array)

['Juan', 'Ramon', 'Anna', 'Julieta', 'Pablo', 'Pedro', 'Gaby', 'Cecilia']
['m', 'm', 'f', 'f', 'm', 'm', 'f', 'f']
<class 'numpy.ndarray'>
['Juan' 'Ramon' 'Anna' 'Julieta' 'Pablo' 'Pedro' 'Gaby' 'Cecilia']